create table filme(
    id number generated by default as identity,
    titulo varchar2(80),
    diretor varchar2(100),
    data_lancamento date,
    sinopse varchar2(400),
    genero varchar2(50),
    nota number(2, 1),
    classificacao varchar2(20),
    primary key(id));