create table tb_time(
    id number generated by default as identity,
    nome varchar2(100),
    vitorias number,
    empates number,
    derrotas number,
    gols_pro number,
    gols_contra number,
    primary key(id)
);

create table tb_partida(
    id number generated by default as identity,
    gols_casa number,
    gols_visitante number,
    rodada number,
    id_casa number,
    id_visitante number,
    primary key(id),
    foreign key (id_casa) references tb_time(id),
    foreign key (id_visitante) references tb_time(id)
);