create table tbv_enquete(
    id number generated by default as identity,
    nome varchar2(100),
    primary key(id)
);

create table tbv_pergunta(
    id number generated by default as identity,
    numero number,
    texto varchar2(200),
    tipo varchar2(20),
    id_enquete number,
    primary key(id),
    foreign key (id_enquete) references tbv_enquete(id) 
);

create table tbv_item(
    id number generated by default as identity,
    numero number,
    descricao varchar2(100),
    id_pergunta number,
    primary key(id),
    foreign key(id_pergunta) references tbv_pergunta(id)
);

create table tbv_pessoa(
    id number generated by default as identity,
    nome varchar2(100),
    idade number,
    genero varchar2(20),
    aplicacao date,
    primary key(id)
);

create table tbv_resposta(
    id number generated by default as identity,
    texto varchar2(200),
    id_pergunta number,
    id_pessoa number,
    primary key(id),
    foreign key(id_pergunta) references tbv_pergunta(id),
    foreign key(id_pessoa) references tbv_pessoa(id)
);

